version: '2.4'

services:
# API
  api:
    container_name: rurall-api
    build:
      context: api
    ports:
      - "3010:3010"
    restart: always
# Client
  client:
    container_name: rurall-client
    build:
      context: client
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: always